apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-exchange
  template:
    metadata:
      labels:
        app: data-exchange
    spec:
      containers:
      - name: writer
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
          - while true; do date >> /data/shared.log; sleep 5; done
        volumeMounts:
        - name: shared-data
          mountPath: /data
      - name: reader
        image: wbitt/network-multitool
        command: ["/bin/sh", "-c"]
        args:
          - tail -f /data/shared.log
        volumeMounts:
        - name: shared-data
          mountPath: /data
      volumes:
      - name: shared-data
        emptyDir: {}
