apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual-local-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/k8s-pv-data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manual-local-pvc
spec:
  volumeName: manual-local-pv
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange-pvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-exchange-pvc
  template:
    metadata:
      labels:
        app: data-exchange-pvc
    spec:
      containers:
      - name: writer
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
          - while true; do date >> /data/pvc.log; sleep 5; done
        volumeMounts:
        - name: pvc-data
          mountPath: /data
      - name: reader
        image: wbitt/network-multitool
        command: ["/bin/sh", "-c"]
        args:
          - tail -f /data/pvc.log
        volumeMounts:
        - name: pvc-data
          mountPath: /data
      volumes:
      - name: pvc-data
        persistentVolumeClaim:
          claimName: manual-local-pvc
