apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-manual-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sc-local-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-manual-sc
  hostPath:
    path: /mnt/k8s-sc-data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sc-local-pvc
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-manual-sc
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange-sc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-exchange-sc
  template:
    metadata:
      labels:
        app: data-exchange-sc
    spec:
      containers:
      - name: writer
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
          - while true; do date >> /data/sc.log; sleep 5; done
        volumeMounts:
        - name: sc-data
          mountPath: /data
      - name: reader
        image: wbitt/network-multitool
        command: ["/bin/sh", "-c"]
        args:
          - tail -f /data/sc.log
        volumeMounts:
        - name: sc-data
          mountPath: /data
      volumes:
      - name: sc-data
        persistentVolumeClaim:
          claimName: sc-local-pvc
